FROM registry.access.redhat.com/ubi9/python-311:latest

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY main.py .

ENV PYTHONUNBUFFERED=1
ENV EVALHUB_MODE=k8s
ENV HF_HOME=/tmp/hf_cache

USER 1001

ENTRYPOINT ["python", "main.py"]
