apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mistral.fullname" . }}-hf-token
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mistral.labels" . | nindent 4 }}
type: Opaque
stringData:
  HF_TOKEN: {{ .Values.secret.hfToken | quote }}
