apiVersion: v1
kind: Secret
metadata:
  name: evalhub-db-credentials
  namespace: redhat-ods-applications
  labels:
    app: evalhub-db
type: Opaque
stringData:
  db-user: "evalhub"
  db-password: "<your-evalhub-db-password>"
  db-url: "postgres://evalhub:<your-evalhub-db-password>@evalhub-db.evalhub.svc:5432/eval_hub"
